name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ./echonet-lite-core
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./echonet-lite-core
  build-mra-reader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ./mra-reader
  test-mra-reader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: davidB/rust-cargo-make@v1
    - name: Run tests
      run: cargo make test-mra-reader
      working-directory: mra-reader
